"""regs db table added

Revision ID: 7a0004106581
Revises: f9978fe11873
Create Date: 2022-05-07 14:49:37.585244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a0004106581'
down_revision = 'f9978fe11873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrationDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('fighter_registration_weight', sa.Integer(), nullable=True),
    sa.Column('fighter_registration_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitionsDB.competition_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('competitionsDB', sa.Column('delete_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitionsDB', 'delete_status')
    op.drop_table('registrationDB')
    # ### end Alembic commands ###
