"""fighters foreighn key

Revision ID: b39e394b658a
Revises: 
Create Date: 2022-05-09 07:45:06.381067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39e394b658a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitionsDB',
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('competition_name', sa.String(), nullable=True),
    sa.Column('competition_date_start', sa.Date(), nullable=True),
    sa.Column('competition_date_finish', sa.Date(), nullable=True),
    sa.Column('competition_city', sa.String(), nullable=True),
    sa.Column('delete_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('competition_id')
    )
    op.create_table('fightersDB',
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('fighter_image_id', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('fighter_id')
    )
    op.create_table('registrationDB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('fighter_id', sa.Integer(), nullable=True),
    sa.Column('fighter_registration_weight', sa.Integer(), nullable=True),
    sa.Column('fighter_registration_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitionsDB.competition_id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['fightersDB.fighter_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrationDB')
    op.drop_table('fightersDB')
    op.drop_table('competitionsDB')
    # ### end Alembic commands ###
